### ISSUE TITLE
CI fails with Terra main branch

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-optimization#138]
### Information

- **Qiskit Optimization version**: main (latest)
- **Python version**: 3.6-3.9
- **Operating system**: Ubuntu (CI)

### What is the current behavior?

CI fails `test.algorithms.test_min_eigen_optimizer.TestMinEigenOptimizer.test_samples_qaoa_2_qasm
`

It is due to Terra's QAOA change https://github.com/Qiskit/qiskit-terra/pull/6396
Details https://github.com/Qiskit/qiskit-terra/issues/6424 and https://github.com/Qiskit/qiskit-terra/issues/6425

### Steps to reproduce the problem

https://github.com/Qiskit/qiskit-optimization/actions/runs/843965790
```python
test.algorithms.test_min_eigen_optimizer.TestMinEigenOptimizer.test_samples_qaoa_2_qasm
---------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)

      File "/home/runner/work/qiskit-optimization/qiskit-optimization/test/algorithms/test_min_eigen_optimizer.py", line 249, in test_samples_qaoa
    self.assertEqual(len(result.raw_samples), 32)

      File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)

      File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)

    AssertionError: 28 != 32
```

### What is the expected behavior?

CI passes the unit tests

### Suggested solutions

We need to wait for update of Terra or merge #136

**Comment by t-imamichi** [comment]
Fixed by #136
