### ISSUE TITLE
QAOAClient with the default argument for initial_point throws an exception

### ISSUE THREAD

**Issue by RaoulHeese** [Qiskit/qiskit-optimization#311]
### Environment

- **Qiskit Optimization version**: 0.3.0
- **Python version**: 3.9.7

### What is happening?

Running the `QAOAClient` with the default argument `initial_point = None` leads to an exception.

Exception message (modified for better readability):

```
RuntimeJobFailureError: 'Unable to retrieve job result. Job xxx has failed:
Traceback (most recent call last):
File "/code/program_starter.py", line 63, in <module>
final_result = main(backend, messenger, **user_params)
File "/code/program.py", line 2418, in main
serialized_inputs["initial_point"] = list(initial_point)
TypeError: 'NoneType' object is not iterable
```

### How can we reproduce the issue?

Run this tutorial: https://qiskit.org/documentation/optimization/tutorials/12_qaoa_runtime.html#Qiskit-optimization

```
from qiskit import IBMQ
from qiskit_optimization.runtime import QAOAClient
from qiskit_optimization.algorithms import MinimumEigenOptimizer
from qiskit_optimization import QuadraticProgram

IBMQ.load_account()
provider = IBMQ.get_provider(hub="ibm-q", group="open", project="main")

qubo = QuadraticProgram()
qubo.binary_var("x")
qubo.binary_var("y")
qubo.binary_var("z")
qubo.minimize(linear=[1, -2, 3], quadratic={("x", "y"): 1, ("x", "z"): -1, ("y", "z"): 2})

qaoa_mes = QAOAClient(
    provider=provider, backend=provider.get_backend("ibmq_qasm_simulator"), reps=2, alpha=0.75
)
qaoa = MinimumEigenOptimizer(qaoa_mes)
qaoa.solve(qubo)
```

### What should happen?

The default value of `inital_point` for `QAOAClient` should be handled in such a way that no exception is thrown. Alternatively, a more informative exception should be used.

### Any suggestions?

Exception is caused by calling `list(None)`.

**Comment by t-imamichi** [comment]
Could you take a look at it, @eggerdj, @Cryoris?

**Comment by t-imamichi** [comment]
Thanks!
