### ISSUE TITLE
``QuadraticProgram.from_ising`` fails on identity terms

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-optimization#354]
### Environment

- **Qiskit Optimization version**: main @ 1779f66
- **Python version**: 3.7.9
- **Operating system**:  macOS Monterey

### What is happening?

Loading a quadratic program from an Ising Hamiltonian fails if the Hamiltonian contains identity terms.

### How can we reproduce the issue?

```python
>>> from qiskit_optimization import QuadraticProgram
>>> from qiskit.opflow import I
>>> qp = QuadraticProgram()
>>> qp.from_ising(I)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jul/Qiskit/qiskit-optimization/qiskit_optimization/problems/quadratic_program.py", line 1014, in from_ising
    other = from_ising(qubit_op, offset, linear)
  File "/Users/jul/Qiskit/qiskit-optimization/qiskit_optimization/translators/ising.py", line 194, in from_ising
    f"There are more than 2 Pauli Zs in the Pauli term: {pauli}"
qiskit_optimization.exceptions.QiskitOptimizationError: 'There are more than 2 Pauli Zs in the Pauli term: I'
```

### What should happen?

The identity term should be included as constant offset.

**Comment by t-imamichi** [comment]
Thank you for the report. I will fix this issue.
